package com.twinkle.dynamic_ms

enum class WidgetItems(val label: String) {
    HEADER("header"),
    TEXT("text"),
    TEXTAREA("textarea"),
    SELECT("select"),
    AUTOTEXT("autoText"),
    RADIO_GROUP("radio-group"),
    PARAGRAPH("paragraph"),
    DATE("date"),
    CHECKBOX_GROUP("checkbox-group"),
    NUMBER("number"),
    MALLABEL("mal_label"),
    MALTEXT("mal_text"),
    LABELS("labels"),
    LABEL("label"),
    TEXTGROUP("text-group"),
    VIEWTEXT("viewText"),
    EDITTEXT("editText"),
    DATETEXT("dateText"),
    NUMBERONE("numberone"),
    FEMALE("female"),
    MALE("male"),
    TAB("tab"),
    TITLEMALEFEMALE("titlemalefemale"),
    TITLETHREEBOXVALUE("titlethreeboxvalue"),
    TITLETWOBOXVALUEMF("titletwoboxvaluemf"),
    DUALMALEFEMALEZERO("dualmalefemalezero"),
    TRIPLE_MF_ZERO("triple_mf_zero"),
    MALOUTINBASE("maloutinbase"),
    SUBTWOZERO("subtwozero"),
    SUBFOURZERO("subfourzero"),
    NUMTEST1("numtest1"),
    THREEVALUEZERO("threevaluezero"),
    MALYRSBASE("malyrsbase"),
    TITLETWOBOXVALUEMF("titletwoboxvaluemf")
}